<?php

return [
    ['country' => 'Afghanistan', 'dialing_code' => '+93', 'flag' => '🇦🇫', 'country_code' => 'AF', 'timezone' => 'Asia/Kabul'],
    ['country' => 'Albania', 'dialing_code' => '+355', 'flag' => '🇦🇱', 'country_code' => 'AL', 'timezone' => 'Europe/Tirane'],
    ['country' => 'Algeria', 'dialing_code' => '+213', 'flag' => '🇩🇿', 'country_code' => 'DZ', 'timezone' => 'Africa/Algiers'],
    ['country' => 'Andorra', 'dialing_code' => '+376', 'flag' => '🇦🇩', 'country_code' => 'AD', 'timezone' => 'Europe/Andorra'],
    ['country' => 'Angola', 'dialing_code' => '+244', 'flag' => '🇦🇴', 'country_code' => 'AO', 'timezone' => 'Africa/Luanda'],
    ['country' => 'Antigua and Barbuda', 'dialing_code' => '+1', 'flag' => '🇦🇬', 'country_code' => 'AG', 'timezone' => 'America/Antigua'],
    ['country' => 'Argentina', 'dialing_code' => '+54', 'flag' => '🇦🇷', 'country_code' => 'AR', 'timezone' => 'America/Argentina/Buenos_Aires'],
    ['country' => 'Armenia', 'dialing_code' => '+374', 'flag' => '🇦🇲', 'country_code' => 'AM', 'timezone' => 'Asia/Yerevan'],
    ['country' => 'Australia', 'dialing_code' => '+61', 'flag' => '🇦🇺', 'country_code' => 'AU', 'timezone' => 'Australia/Sydney'],
    ['country' => 'Austria', 'dialing_code' => '+43', 'flag' => '🇦🇹', 'country_code' => 'AT', 'timezone' => 'Europe/Vienna'],
    ['country' => 'Azerbaijan', 'dialing_code' => '+994', 'flag' => '🇦🇿', 'country_code' => 'AZ', 'timezone' => 'Asia/Baku'],
    ['country' => 'Bahamas', 'dialing_code' => '+1', 'flag' => '🇧🇸', 'country_code' => 'BS', 'timezone' => 'America/Nassau'],
    ['country' => 'Bahrain', 'dialing_code' => '+973', 'flag' => '🇧🇭', 'country_code' => 'BH', 'timezone' => 'Asia/Bahrain'],
    ['country' => 'Bangladesh', 'dialing_code' => '+880', 'flag' => '🇧🇩', 'country_code' => 'BD', 'timezone' => 'Asia/Dhaka'],
    ['country' => 'Barbados', 'dialing_code' => '+1', 'flag' => '🇧🇧', 'country_code' => 'BB', 'timezone' => 'America/Barbados'],
    ['country' => 'Belarus', 'dialing_code' => '+375', 'flag' => '🇧🇾', 'country_code' => 'BY', 'timezone' => 'Europe/Minsk'],
    ['country' => 'Belgium', 'dialing_code' => '+32', 'flag' => '🇧🇪', 'country_code' => 'BE', 'timezone' => 'Europe/Brussels'],
    ['country' => 'Belize', 'dialing_code' => '+501', 'flag' => '🇧🇿', 'country_code' => 'BZ', 'timezone' => 'America/Belize'],
    ['country' => 'Benin', 'dialing_code' => '+229', 'flag' => '🇧🇯', 'country_code' => 'BJ', 'timezone' => 'Africa/Porto-Novo'],
    ['country' => 'Bhutan', 'dialing_code' => '+975', 'flag' => '🇧🇹', 'country_code' => 'BT', 'timezone' => 'Asia/Thimphu'],
    ['country' => 'Bolivia (Plurinational State of)', 'dialing_code' => '+591', 'flag' => '🇧🇴', 'country_code' => 'BO', 'timezone' => 'America/La_Paz'],
    ['country' => 'Bosnia and Herzegovina', 'dialing_code' => '+387', 'flag' => '🇧🇦', 'country_code' => 'BA', 'timezone' => 'Europe/Sarajevo'],
    ['country' => 'Botswana', 'dialing_code' => '+267', 'flag' => '🇧🇼', 'country_code' => 'BW', 'timezone' => 'Africa/Gaborone'],
    ['country' => 'Brazil', 'dialing_code' => '+55', 'flag' => '🇧🇷', 'country_code' => 'BR', 'timezone' => 'America/Sao_Paulo'],
    ['country' => 'Brunei Darussalam', 'dialing_code' => '+673', 'flag' => '🇧🇳', 'country_code' => 'BN', 'timezone' => 'Asia/Brunei'],
    ['country' => 'Bulgaria', 'dialing_code' => '+359', 'flag' => '🇧🇬', 'country_code' => 'BG', 'timezone' => 'Europe/Sofia'],
    ['country' => 'Burkina Faso', 'dialing_code' => '+226', 'flag' => '🇧🇫', 'country_code' => 'BF', 'timezone' => 'Africa/Ouagadougou'],
    ['country' => 'Burundi', 'dialing_code' => '+257', 'flag' => '🇧🇮', 'country_code' => 'BI', 'timezone' => 'Africa/Bujumbura'],
    ['country' => 'Cabo Verde', 'dialing_code' => '+238', 'flag' => '🇨🇻', 'country_code' => 'CV', 'timezone' => 'Atlantic/Cape_Verde'],
    ['country' => 'Cambodia', 'dialing_code' => '+855', 'flag' => '🇰🇭', 'country_code' => 'KH', 'timezone' => 'Asia/Phnom_Penh'],
    ['country' => 'Cameroon', 'dialing_code' => '+237', 'flag' => '🇨🇲', 'country_code' => 'CM', 'timezone' => 'Africa/Douala'],
    ['country' => 'Canada', 'dialing_code' => '+1', 'flag' => '🇨🇦', 'country_code' => 'CA', 'timezone' => 'America/Toronto'],
    ['country' => 'Central African Republic', 'dialing_code' => '+236', 'flag' => '🇨🇫', 'country_code' => 'CF', 'timezone' => 'Africa/Bangui'],
    ['country' => 'Chad', 'dialing_code' => '+235', 'flag' => '🇹🇩', 'country_code' => 'TD', 'timezone' => 'Africa/Ndjamena'],
    ['country' => 'Chile', 'dialing_code' => '+56', 'flag' => '🇨🇱', 'country_code' => 'CL', 'timezone' => 'America/Santiago'],
    ['country' => 'China', 'dialing_code' => '+86', 'flag' => '🇨🇳', 'country_code' => 'CN', 'timezone' => 'Asia/Shanghai'],
    ['country' => 'Colombia', 'dialing_code' => '+57', 'flag' => '🇨🇴', 'country_code' => 'CO', 'timezone' => 'America/Bogota'],
    ['country' => 'Comoros', 'dialing_code' => '+269', 'flag' => '🇰🇲', 'country_code' => 'KM', 'timezone' => 'Indian/Comoro'],
    ['country' => 'Congo', 'dialing_code' => '+242', 'flag' => '🇨🇬', 'country_code' => 'CG', 'timezone' => 'Africa/Brazzaville'],
    ['country' => 'Costa Rica', 'dialing_code' => '+506', 'flag' => '🇨🇷', 'country_code' => 'CR', 'timezone' => 'America/Costa_Rica'],
    ['country' => 'Croatia', 'dialing_code' => '+385', 'flag' => '🇭🇷', 'country_code' => 'HR', 'timezone' => 'Europe/Zagreb'],
    ['country' => 'Cuba', 'dialing_code' => '+53', 'flag' => '🇨🇺', 'country_code' => 'CU', 'timezone' => 'America/Havana'],
    ['country' => 'Cyprus', 'dialing_code' => '+357', 'flag' => '🇨🇾', 'country_code' => 'CY', 'timezone' => 'Asia/Nicosia'],
    ['country' => 'Czech Republic', 'dialing_code' => '+420', 'flag' => '🇨🇿', 'country_code' => 'CZ', 'timezone' => 'Europe/Prague'],
    ['country' => 'Democratic Republic of the Congo', 'dialing_code' => '+243', 'flag' => '🇨🇩', 'country_code' => 'CD', 'timezone' => 'Africa/Kinshasa'],
    ['country' => 'Denmark', 'dialing_code' => '+45', 'flag' => '🇩🇰', 'country_code' => 'DK', 'timezone' => 'Europe/Copenhagen'],
    ['country' => 'Djibouti', 'dialing_code' => '+253', 'flag' => '🇩🇯', 'country_code' => 'DJ', 'timezone' => 'Africa/Djibouti'],
    ['country' => 'Dominica', 'dialing_code' => '+1', 'flag' => '🇩🇲', 'country_code' => 'DM', 'timezone' => 'America/Dominica'],
    ['country' => 'Dominican Republic', 'dialing_code' => '+1', 'flag' => '🇩🇴', 'country_code' => 'DO', 'timezone' => 'America/Santo_Domingo'],
    ['country' => 'Ecuador', 'dialing_code' => '+593', 'flag' => '🇪🇨', 'country_code' => 'EC', 'timezone' => 'America/Guayaquil'],
    ['country' => 'Egypt', 'dialing_code' => '+20', 'flag' => '🇪🇬', 'country_code' => 'EG', 'timezone' => 'Africa/Cairo'],
    ['country' => 'El Salvador', 'dialing_code' => '+503', 'flag' => '🇸🇻', 'country_code' => 'SV', 'timezone' => 'America/El_Salvador'],
    ['country' => 'Equatorial Guinea', 'dialing_code' => '+240', 'flag' => '🇬🇶', 'country_code' => 'GQ', 'timezone' => 'Africa/Malabo'],
    ['country' => 'Eritrea', 'dialing_code' => '+291', 'flag' => '🇪🇷', 'country_code' => 'ER', 'timezone' => 'Africa/Asmara'],
    ['country' => 'Estonia', 'dialing_code' => '+372', 'flag' => '🇪🇪', 'country_code' => 'EE', 'timezone' => 'Europe/Tallinn'],
    ['country' => 'Eswatini', 'dialing_code' => '+268', 'flag' => '🇸🇿', 'country_code' => 'SZ', 'timezone' => 'Africa/Mbabane'],
    ['country' => 'Ethiopia', 'dialing_code' => '+251', 'flag' => '🇪🇹', 'country_code' => 'ET', 'timezone' => 'Africa/Addis_Ababa'],
    ['country' => 'Fiji', 'dialing_code' => '+679', 'flag' => '🇫🇯', 'country_code' => 'FJ', 'timezone' => 'Pacific/Fiji'],
    ['country' => 'Finland', 'dialing_code' => '+358', 'flag' => '🇫🇮', 'country_code' => 'FI', 'timezone' => 'Europe/Helsinki'],
    ['country' => 'France', 'dialing_code' => '+33', 'flag' => '🇫🇷', 'country_code' => 'FR', 'timezone' => 'Europe/Paris'],
    ['country' => 'Gabon', 'dialing_code' => '+241', 'flag' => '🇬🇦', 'country_code' => 'GA', 'timezone' => 'Africa/Libreville'],
    ['country' => 'Gambia', 'dialing_code' => '+220', 'flag' => '🇬🇲', 'country_code' => 'GM', 'timezone' => 'Africa/Banjul'],
    ['country' => 'Georgia', 'dialing_code' => '+995', 'flag' => '🇬🇪', 'country_code' => 'GE', 'timezone' => 'Asia/Tbilisi'],
    ['country' => 'Germany', 'dialing_code' => '+49', 'flag' => '🇩🇪', 'country_code' => 'DE', 'timezone' => 'Europe/Berlin'],
    ['country' => 'Ghana', 'dialing_code' => '+233', 'flag' => '🇬🇭', 'country_code' => 'GH', 'timezone' => 'Africa/Accra'],
    ['country' => 'Greece', 'dialing_code' => '+30', 'flag' => '🇬🇷', 'country_code' => 'GR', 'timezone' => 'Europe/Athens'],
    ['country' => 'Grenada', 'dialing_code' => '+1', 'flag' => '🇬🇩', 'country_code' => 'GD', 'timezone' => 'America/Grenada'],
    ['country' => 'Guatemala', 'dialing_code' => '+502', 'flag' => '🇬🇹', 'country_code' => 'GT', 'timezone' => 'America/Guatemala'],
    ['country' => 'Guinea', 'dialing_code' => '+224', 'flag' => '🇬🇳', 'country_code' => 'GN', 'timezone' => 'Africa/Conakry'],
    ['country' => 'Guinea-Bissau', 'dialing_code' => '+245', 'flag' => '🇬🇼', 'country_code' => 'GW', 'timezone' => 'Africa/Bissau'],
    ['country' => 'Guyana', 'dialing_code' => '+592', 'flag' => '🇬🇾', 'country_code' => 'GY', 'timezone' => 'America/Guyana'],
    ['country' => 'Haiti', 'dialing_code' => '+509', 'flag' => '🇭🇹', 'country_code' => 'HT', 'timezone' => 'America/Port-au-Prince'],
    ['country' => 'Honduras', 'dialing_code' => '+504', 'flag' => '🇭🇳', 'country_code' => 'HN', 'timezone' => 'America/Tegucigalpa'],
    ['country' => 'Hungary', 'dialing_code' => '+36', 'flag' => '🇭🇺', 'country_code' => 'HU', 'timezone' => 'Europe/Budapest'],
    ['country' => 'Iceland', 'dialing_code' => '+354', 'flag' => '🇮🇸', 'country_code' => 'IS', 'timezone' => 'Atlantic/Reykjavik'],
    ['country' => 'India', 'dialing_code' => '+91', 'flag' => '🇮🇳', 'country_code' => 'IN', 'timezone' => 'Asia/Kolkata'],
    ['country' => 'Indonesia', 'dialing_code' => '+62', 'flag' => '🇮🇩', 'country_code' => 'ID', 'timezone' => 'Asia/Jakarta'],
    ['country' => 'Iran', 'dialing_code' => '+98', 'flag' => '🇮🇷', 'country_code' => 'IR', 'timezone' => 'Asia/Tehran'],
    ['country' => 'Iraq', 'dialing_code' => '+964', 'flag' => '🇮🇶', 'country_code' => 'IQ', 'timezone' => 'Asia/Baghdad'],
    ['country' => 'Ireland', 'dialing_code' => '+353', 'flag' => '🇮🇪', 'country_code' => 'IE', 'timezone' => 'Europe/Dublin'],
    ['country' => 'Israel', 'dialing_code' => '+972', 'flag' => '🇮🇱', 'country_code' => 'IL', 'timezone' => 'Asia/Jerusalem'],
    ['country' => 'Italy', 'dialing_code' => '+39', 'flag' => '🇮🇹', 'country_code' => 'IT', 'timezone' => 'Europe/Rome'],
    ['country' => 'Jamaica', 'dialing_code' => '+1', 'flag' => '🇯🇲', 'country_code' => 'JM', 'timezone' => 'America/Jamaica'],
    ['country' => 'Japan', 'dialing_code' => '+81', 'flag' => '🇯🇵', 'country_code' => 'JP', 'timezone' => 'Asia/Tokyo'],
    ['country' => 'Jordan', 'dialing_code' => '+962', 'flag' => '🇯🇴', 'country_code' => 'JO', 'timezone' => 'Asia/Amman'],
    ['country' => 'Kazakhstan', 'dialing_code' => '+7', 'flag' => '🇰🇿', 'country_code' => 'KZ', 'timezone' => 'Asia/Almaty'],
    ['country' => 'Kenya', 'dialing_code' => '+254', 'flag' => '🇰🇪', 'country_code' => 'KE', 'timezone' => 'Africa/Nairobi'],
    ['country' => 'Kiribati', 'dialing_code' => '+686', 'flag' => '🇰🇮', 'country_code' => 'KI', 'timezone' => 'Pacific/Tarawa'],
    ['country' => 'Kuwait', 'dialing_code' => '+965', 'flag' => '🇰🇼', 'country_code' => 'KW', 'timezone' => 'Asia/Kuwait'],
    ['country' => 'Kyrgyzstan', 'dialing_code' => '+996', 'flag' => '🇰🇬', 'country_code' => 'KG', 'timezone' => 'Asia/Bishkek'],
    ['country' => 'Laos', 'dialing_code' => '+856', 'flag' => '🇱🇦', 'country_code' => 'LA', 'timezone' => 'Asia/Vientiane'],
    ['country' => 'Latvia', 'dialing_code' => '+371', 'flag' => '🇱🇻', 'country_code' => 'LV', 'timezone' => 'Europe/Riga'],
    ['country' => 'Lebanon', 'dialing_code' => '+961', 'flag' => '🇱🇧', 'country_code' => 'LB', 'timezone' => 'Asia/Beirut'],
    ['country' => 'Lesotho', 'dialing_code' => '+266', 'flag' => '🇱🇸', 'country_code' => 'LS', 'timezone' => 'Africa/Maseru'],
    ['country' => 'Liberia', 'dialing_code' => '+231', 'flag' => '🇱🇷', 'country_code' => 'LR', 'timezone' => 'Africa/Monrovia'],
    ['country' => 'Libya', 'dialing_code' => '+218', 'flag' => '🇱🇾', 'country_code' => 'LY', 'timezone' => 'Africa/Tripoli'],
    ['country' => 'Liechtenstein', 'dialing_code' => '+423', 'flag' => '🇱🇮', 'country_code' => 'LI', 'timezone' => 'Europe/Vaduz'],
    ['country' => 'Lithuania', 'dialing_code' => '+370', 'flag' => '🇱🇹', 'country_code' => 'LT', 'timezone' => 'Europe/Vilnius'],
    ['country' => 'Luxembourg', 'dialing_code' => '+352', 'flag' => '🇱🇺', 'country_code' => 'LU', 'timezone' => 'Europe/Luxembourg'],
    ['country' => 'Madagascar', 'dialing_code' => '+261', 'flag' => '🇲🇬', 'country_code' => 'MG', 'timezone' => 'Indian/Antananarivo'],
    ['country' => 'Malawi', 'dialing_code' => '+265', 'flag' => '🇲🇼', 'country_code' => 'MW', 'timezone' => 'Africa/Blantyre'],
    ['country' => 'Malaysia', 'dialing_code' => '+60', 'flag' => '🇲🇾', 'country_code' => 'MY', 'timezone' => 'Asia/Kuala_Lumpur'],
    ['country' => 'Maldives', 'dialing_code' => '+960', 'flag' => '🇲🇻', 'country_code' => 'MV', 'timezone' => 'Indian/Maldives'],
    ['country' => 'Mali', 'dialing_code' => '+223', 'flag' => '🇲🇱', 'country_code' => 'ML', 'timezone' => 'Africa/Bamako'],
    ['country' => 'Malta', 'dialing_code' => '+356', 'flag' => '🇲🇹', 'country_code' => 'MT', 'timezone' => 'Europe/Malta'],
    ['country' => 'Marshall Islands', 'dialing_code' => '+692', 'flag' => '🇲🇭', 'country_code' => 'MH', 'timezone' => 'Pacific/Majuro'],
    ['country' => 'Mauritania', 'dialing_code' => '+222', 'flag' => '🇲🇷', 'country_code' => 'MR', 'timezone' => 'Africa/Nouakchott'],
    ['country' => 'Mauritius', 'dialing_code' => '+230', 'flag' => '🇲🇺', 'country_code' => 'MU', 'timezone' => 'Indian/Mauritius'],
    ['country' => 'Mexico', 'dialing_code' => '+52', 'flag' => '🇲🇽', 'country_code' => 'MX', 'timezone' => 'America/Mexico_City'],
    ['country' => 'Micronesia', 'dialing_code' => '+691', 'flag' => '🇫🇲', 'country_code' => 'FM', 'timezone' => 'Pacific/Pohnpei'],
    ['country' => 'Moldova', 'dialing_code' => '+373', 'flag' => '🇲🇩', 'country_code' => 'MD', 'timezone' => 'Europe/Chisinau'],
    ['country' => 'Monaco', 'dialing_code' => '+377', 'flag' => '🇲🇨', 'country_code' => 'MC', 'timezone' => 'Europe/Monaco'],
    ['country' => 'Mongolia', 'dialing_code' => '+976', 'flag' => '🇲🇳', 'country_code' => 'MN', 'timezone' => 'Asia/Ulaanbaatar'],
    ['country' => 'Montenegro', 'dialing_code' => '+382', 'flag' => '🇲🇪', 'country_code' => 'ME', 'timezone' => 'Europe/Podgorica'],
    ['country' => 'Morocco', 'dialing_code' => '+212', 'flag' => '🇲🇦', 'country_code' => 'MA', 'timezone' => 'Africa/Casablanca'],
    ['country' => 'Mozambique', 'dialing_code' => '+258', 'flag' => '🇲🇿', 'country_code' => 'MZ', 'timezone' => 'Africa/Maputo'],
    ['country' => 'Myanmar', 'dialing_code' => '+95', 'flag' => '🇲🇲', 'country_code' => 'MM', 'timezone' => 'Asia/Yangon'],
    ['country' => 'Namibia', 'dialing_code' => '+264', 'flag' => '🇳🇦', 'country_code' => 'NA', 'timezone' => 'Africa/Windhoek'],
    ['country' => 'Nauru', 'dialing_code' => '+674', 'flag' => '🇳🇷', 'country_code' => 'NR', 'timezone' => 'Pacific/Nauru'],
    ['country' => 'Nepal', 'dialing_code' => '+977', 'flag' => '🇳🇵', 'country_code' => 'NP', 'timezone' => 'Asia/Kathmandu'],
    ['country' => 'Netherlands', 'dialing_code' => '+31', 'flag' => '🇳🇱', 'country_code' => 'NL', 'timezone' => 'Europe/Amsterdam'],
    ['country' => 'New Zealand', 'dialing_code' => '+64', 'flag' => '🇳🇿', 'country_code' => 'NZ', 'timezone' => 'Pacific/Auckland'],
    ['country' => 'Nicaragua', 'dialing_code' => '+505', 'flag' => '🇳🇮', 'country_code' => 'NI', 'timezone' => 'America/Managua'],
    ['country' => 'Niger', 'dialing_code' => '+227', 'flag' => '🇳🇪', 'country_code' => 'NE', 'timezone' => 'Africa/Niamey'],
    ['country' => 'Nigeria', 'dialing_code' => '+234', 'flag' => '🇳🇬', 'country_code' => 'NG', 'timezone' => 'Africa/Lagos'],
    ['country' => 'North Korea', 'dialing_code' => '+850', 'flag' => '🇰🇵', 'country_code' => 'KP', 'timezone' => 'Asia/Pyongyang'],
    ['country' => 'North Macedonia', 'dialing_code' => '+389', 'flag' => '🇲🇰', 'country_code' => 'MK', 'timezone' => 'Europe/Skopje'],
    ['country' => 'Norway', 'dialing_code' => '+47', 'flag' => '🇳🇴', 'country_code' => 'NO', 'timezone' => 'Europe/Oslo'],
    ['country' => 'Oman', 'dialing_code' => '+968', 'flag' => '🇴🇲', 'country_code' => 'OM', 'timezone' => 'Asia/Muscat'],
    ['country' => 'Pakistan', 'dialing_code' => '+92', 'flag' => '🇵🇰', 'country_code' => 'PK', 'timezone' => 'Asia/Karachi'],
    ['country' => 'Palau', 'dialing_code' => '+680', 'flag' => '🇵🇼', 'country_code' => 'PW', 'timezone' => 'Pacific/Palau'],
    ['country' => 'Palestine', 'dialing_code' => '+970', 'flag' => '🇵🇸', 'country_code' => 'PS', 'timezone' => 'Asia/Gaza'],
    ['country' => 'Panama', 'dialing_code' => '+507', 'flag' => '🇵🇦', 'country_code' => 'PA', 'timezone' => 'America/Panama'],
    ['country' => 'Papua New Guinea', 'dialing_code' => '+675', 'flag' => '🇵🇬', 'country_code' => 'PG', 'timezone' => 'Pacific/Port_Moresby'],
    ['country' => 'Paraguay', 'dialing_code' => '+595', 'flag' => '🇵🇾', 'country_code' => 'PY', 'timezone' => 'America/Asuncion'],
    ['country' => 'Peru', 'dialing_code' => '+51', 'flag' => '🇵🇪', 'country_code' => 'PE', 'timezone' => 'America/Lima'],
    ['country' => 'Philippines', 'dialing_code' => '+63', 'flag' => '🇵🇭', 'country_code' => 'PH', 'timezone' => 'Asia/Manila'],
    ['country' => 'Poland', 'dialing_code' => '+48', 'flag' => '🇵🇱', 'country_code' => 'PL', 'timezone' => 'Europe/Warsaw'],
    ['country' => 'Portugal', 'dialing_code' => '+351', 'flag' => '🇵🇹', 'country_code' => 'PT', 'timezone' => 'Europe/Lisbon'],
    ['country' => 'Qatar', 'dialing_code' => '+974', 'flag' => '🇶🇦', 'country_code' => 'QA', 'timezone' => 'Asia/Qatar'],
    ['country' => 'Romania', 'dialing_code' => '+40', 'flag' => '🇷🇴', 'country_code' => 'RO', 'timezone' => 'Europe/Bucharest'],
    ['country' => 'Russia', 'dialing_code' => '+7', 'flag' => '🇷🇺', 'country_code' => 'RU', 'timezone' => 'Europe/Moscow'],
    ['country' => 'Rwanda', 'dialing_code' => '+250', 'flag' => '🇷🇼', 'country_code' => 'RW', 'timezone' => 'Africa/Kigali'],
    ['country' => 'Saint Kitts and Nevis', 'dialing_code' => '+1', 'flag' => '🇰🇳', 'country_code' => 'KN', 'timezone' => 'America/St_Kitts'],
    ['country' => 'Saint Lucia', 'dialing_code' => '+1', 'flag' => '🇱🇨', 'country_code' => 'LC', 'timezone' => 'America/St_Lucia'],
    ['country' => 'Saint Vincent and the Grenadines', 'dialing_code' => '+1', 'flag' => '🇻🇨', 'country_code' => 'VC', 'timezone' => 'America/St_Vincent'],
    ['country' => 'Samoa', 'dialing_code' => '+685', 'flag' => '🇼🇸', 'country_code' => 'WS', 'timezone' => 'Pacific/Apia'],
    ['country' => 'San Marino', 'dialing_code' => '+378', 'flag' => '🇸🇲', 'country_code' => 'SM', 'timezone' => 'Europe/San_Marino'],
    ['country' => 'Saudi Arabia', 'dialing_code' => '+966', 'flag' => '🇸🇦', 'country_code' => 'SA', 'timezone' => 'Asia/Riyadh'],
    ['country' => 'Senegal', 'dialing_code' => '+221', 'flag' => '🇸🇳', 'country_code' => 'SN', 'timezone' => 'Africa/Dakar'],
    ['country' => 'Serbia', 'dialing_code' => '+381', 'flag' => '🇷🇸', 'country_code' => 'RS', 'timezone' => 'Europe/Belgrade'],
    ['country' => 'Seychelles', 'dialing_code' => '+248', 'flag' => '🇸🇨', 'country_code' => 'SC', 'timezone' => 'Indian/Mahe'],
    ['country' => 'Sierra Leone', 'dialing_code' => '+232', 'flag' => '🇸🇱', 'country_code' => 'SL', 'timezone' => 'Africa/Freetown'],
    ['country' => 'Singapore', 'dialing_code' => '+65', 'flag' => '🇸🇬', 'country_code' => 'SG', 'timezone' => 'Asia/Singapore'],
    ['country' => 'Slovakia', 'dialing_code' => '+421', 'flag' => '🇸🇰', 'country_code' => 'SK', 'timezone' => 'Europe/Bratislava'],
    ['country' => 'Slovenia', 'dialing_code' => '+386', 'flag' => '🇸🇮', 'country_code' => 'SI', 'timezone' => 'Europe/Ljubljana'],
    ['country' => 'Solomon Islands', 'dialing_code' => '+677', 'flag' => '🇸🇧', 'country_code' => 'SB', 'timezone' => 'Pacific/Guadalcanal'],
    ['country' => 'Somalia', 'dialing_code' => '+252', 'flag' => '🇸🇴', 'country_code' => 'SO', 'timezone' => 'Africa/Mogadishu'],
    ['country' => 'South Africa', 'dialing_code' => '+27', 'flag' => '🇿🇦', 'country_code' => 'ZA', 'timezone' => 'Africa/Johannesburg'],
    ['country' => 'South Korea', 'dialing_code' => '+82', 'flag' => '🇰🇷', 'country_code' => 'KR', 'timezone' => 'Asia/Seoul'],
    ['country' => 'South Sudan', 'dialing_code' => '+211', 'flag' => '🇸🇸', 'country_code' => 'SS', 'timezone' => 'Africa/Juba'],
    ['country' => 'Spain', 'dialing_code' => '+34', 'flag' => '🇪🇸', 'country_code' => 'ES', 'timezone' => 'Europe/Madrid'],
    ['country' => 'Sri Lanka', 'dialing_code' => '+94', 'flag' => '🇱🇰', 'country_code' => 'LK', 'timezone' => 'Asia/Colombo'],
    ['country' => 'Sudan', 'dialing_code' => '+249', 'flag' => '🇸🇩', 'country_code' => 'SD', 'timezone' => 'Africa/Khartoum'],
    ['country' => 'Suriname', 'dialing_code' => '+597', 'flag' => '🇸🇷', 'country_code' => 'SR', 'timezone' => 'America/Paramaribo'],
    ['country' => 'Sweden', 'dialing_code' => '+46', 'flag' => '🇸🇪', 'country_code' => 'SE', 'timezone' => 'Europe/Stockholm'],
    ['country' => 'Switzerland', 'dialing_code' => '+41', 'flag' => '🇨🇭', 'country_code' => 'CH', 'timezone' => 'Europe/Zurich'],
    ['country' => 'Syria', 'dialing_code' => '+963', 'flag' => '🇸🇾', 'country_code' => 'SY', 'timezone' => 'Asia/Damascus'],
    ['country' => 'Taiwan', 'dialing_code' => '+886', 'flag' => '🇹🇼', 'country_code' => 'TW', 'timezone' => 'Asia/Taipei'],
    ['country' => 'Tajikistan', 'dialing_code' => '+992', 'flag' => '🇹🇯', 'country_code' => 'TJ', 'timezone' => 'Asia/Dushanbe'],
    ['country' => 'Tanzania', 'dialing_code' => '+255', 'flag' => '🇹🇿', 'country_code' => 'TZ', 'timezone' => 'Africa/Dar_es_Salaam'],
    ['country' => 'Thailand', 'dialing_code' => '+66', 'flag' => '🇹🇭', 'country_code' => 'TH', 'timezone' => 'Asia/Bangkok'],
    ['country' => 'Timor-Leste', 'dialing_code' => '+670', 'flag' => '🇹🇱', 'country_code' => 'TL', 'timezone' => 'Asia/Dili'],
    ['country' => 'Togo', 'dialing_code' => '+228', 'flag' => '🇹🇬', 'country_code' => 'TG', 'timezone' => 'Africa/Lome'],
    ['country' => 'Tonga', 'dialing_code' => '+676', 'flag' => '🇹🇴', 'country_code' => 'TO', 'timezone' => 'Pacific/Tongatapu'],
    ['country' => 'Trinidad and Tobago', 'dialing_code' => '+1', 'flag' => '🇹🇹', 'country_code' => 'TT', 'timezone' => 'America/Port_of_Spain'],
    ['country' => 'Tunisia', 'dialing_code' => '+216', 'flag' => '🇹🇳', 'country_code' => 'TN', 'timezone' => 'Africa/Tunis'],
    ['country' => 'Turkey', 'dialing_code' => '+90', 'flag' => '🇹🇷', 'country_code' => 'TR', 'timezone' => 'Europe/Istanbul'],
    ['country' => 'Turkmenistan', 'dialing_code' => '+993', 'flag' => '🇹🇲', 'country_code' => 'TM', 'timezone' => 'Asia/Ashgabat'],
    ['country' => 'Tuvalu', 'dialing_code' => '+688', 'flag' => '🇹🇻', 'country_code' => 'TV', 'timezone' => 'Pacific/Funafuti'],
    ['country' => 'Uganda', 'dialing_code' => '+256', 'flag' => '🇺🇬', 'country_code' => 'UG', 'timezone' => 'Africa/Kampala'],
    ['country' => 'Ukraine', 'dialing_code' => '+380', 'flag' => '🇺🇦', 'country_code' => 'UA', 'timezone' => 'Europe/Kyiv'],
    ['country' => 'United Arab Emirates', 'dialing_code' => '+971', 'flag' => '🇦🇪', 'country_code' => 'AE', 'timezone' => 'Asia/Dubai'],
    ['country' => 'United Kingdom', 'dialing_code' => '+44', 'flag' => '🇬🇧', 'country_code' => 'GB', 'timezone' => 'Europe/London'],
    ['country' => 'United States', 'dialing_code' => '+1', 'flag' => '🇺🇸', 'country_code' => 'US', 'timezone' => 'America/New_York'],
    ['country' => 'Uruguay', 'dialing_code' => '+598', 'flag' => '🇺🇾', 'country_code' => 'UY', 'timezone' => 'America/Montevideo'],
    ['country' => 'Uzbekistan', 'dialing_code' => '+998', 'flag' => '🇺🇿', 'country_code' => 'UZ', 'timezone' => 'Asia/Tashkent'],
    ['country' => 'Vanuatu', 'dialing_code' => '+678', 'flag' => '🇻🇺', 'country_code' => 'VU', 'timezone' => 'Pacific/Efate'],
    ['country' => 'Vatican City', 'dialing_code' => '+379', 'flag' => '🇻🇦', 'country_code' => 'VA', 'timezone' => 'Europe/Vatican'],
    ['country' => 'Venezuela', 'dialing_code' => '+58', 'flag' => '🇻🇪', 'country_code' => 'VE', 'timezone' => 'America/Caracas'],
    ['country' => 'Vietnam', 'dialing_code' => '+84', 'flag' => '🇻🇳', 'country_code' => 'VN', 'timezone' => 'Asia/Ho_Chi_Minh'],
    ['country' => 'Yemen', 'dialing_code' => '+967', 'flag' => '🇾🇪', 'country_code' => 'YE', 'timezone' => 'Asia/Aden'],
    ['country' => 'Zambia', 'dialing_code' => '+260', 'flag' => '🇿🇲', 'country_code' => 'ZM', 'timezone' => 'Africa/Lusaka'],
    ['country' => 'Zimbabwe', 'dialing_code' => '+263', 'flag' => '🇿🇼', 'country_code' => 'ZW', 'timezone' => 'Africa/Harare'],
];
