<?php 

return [
  ['country' => 'Afghanistan', 'dialing_code' => '+93', 'flag' => '🇦🇫', 'timezone' => 'Asia/Kabul'],
  ['country' => 'Albania', 'dialing_code' => '+355', 'flag' => '🇦🇱', 'timezone' => 'Europe/Tirane'],
  ['country' => 'Algeria', 'dialing_code' => '+213', 'flag' => '🇩🇿', 'timezone' => 'Africa/Algiers'],
  ['country' => 'Andorra', 'dialing_code' => '+376', 'flag' => '🇦🇩', 'timezone' => 'Europe/Andorra'],
  ['country' => 'Angola', 'dialing_code' => '+244', 'flag' => '🇦🇴', 'timezone' => 'Africa/Luanda'],
  ['country' => 'Antigua and Barbuda', 'dialing_code' => '+1', 'flag' => '🇦🇬', 'timezone' => 'America/Antigua'],
  ['country' => 'Argentina', 'dialing_code' => '+54', 'flag' => '🇦🇷', 'timezone' => 'America/Argentina/Buenos_Aires'],
  ['country' => 'Armenia', 'dialing_code' => '+374', 'flag' => '🇦🇲', 'timezone' => 'Asia/Yerevan'],
  ['country' => 'Australia', 'dialing_code' => '+61', 'flag' => '🇦🇺', 'timezone' => 'Australia/Sydney'],
  ['country' => 'Austria', 'dialing_code' => '+43', 'flag' => '🇦🇹', 'timezone' => 'Europe/Vienna'],
  ['country' => 'Azerbaijan', 'dialing_code' => '+994', 'flag' => '🇦🇿', 'timezone' => 'Asia/Baku'],
  ['country' => 'Bahamas', 'dialing_code' => '+1', 'flag' => '🇧🇸', 'timezone' => 'America/Nassau'],
  ['country' => 'Bahrain', 'dialing_code' => '+973', 'flag' => '🇧🇭', 'timezone' => 'Asia/Bahrain'],
  ['country' => 'Bangladesh', 'dialing_code' => '+880', 'flag' => '🇧🇩', 'timezone' => 'Asia/Dhaka'],
  ['country' => 'Barbados', 'dialing_code' => '+1', 'flag' => '🇧🇧', 'timezone' => 'America/Barbados'],
  ['country' => 'Belarus', 'dialing_code' => '+375', 'flag' => '🇧🇾', 'timezone' => 'Europe/Minsk'],
  ['country' => 'Belgium', 'dialing_code' => '+32', 'flag' => '🇧🇪', 'timezone' => 'Europe/Brussels'],
  ['country' => 'Belize', 'dialing_code' => '+501', 'flag' => '🇧🇿', 'timezone' => 'America/Belize'],
  ['country' => 'Benin', 'dialing_code' => '+229', 'flag' => '🇧🇯', 'timezone' => 'Africa/Porto-Novo'],
  ['country' => 'Bhutan', 'dialing_code' => '+975', 'flag' => '🇧🇹', 'timezone' => 'Asia/Thimphu'],
  ['country' => 'Bolivia (Plurinational State of)', 'dialing_code' => '+591', 'flag' => '🇧🇴', 'timezone' => 'America/La_Paz'],
  ['country' => 'Bosnia and Herzegovina', 'dialing_code' => '+387', 'flag' => '🇧🇦', 'timezone' => 'Europe/Sarajevo'],
  ['country' => 'Botswana', 'dialing_code' => '+267', 'flag' => '🇧🇼', 'timezone' => 'Africa/Gaborone'],
  ['country' => 'Brazil', 'dialing_code' => '+55', 'flag' => '🇧🇷', 'timezone' => 'America/Sao_Paulo'],
  ['country' => 'Brunei Darussalam', 'dialing_code' => '+673', 'flag' => '🇧🇳', 'timezone' => 'Asia/Brunei'],
  ['country' => 'Bulgaria', 'dialing_code' => '+359', 'flag' => '🇧🇬', 'timezone' => 'Europe/Sofia'],
  ['country' => 'Burkina Faso', 'dialing_code' => '+226', 'flag' => '🇧🇫', 'timezone' => 'Africa/Ouagadougou'],
  ['country' => 'Burundi', 'dialing_code' => '+257', 'flag' => '🇧🇮', 'timezone' => 'Africa/Bujumbura'],
  ['country' => 'Cabo Verde', 'dialing_code' => '+238', 'flag' => '🇨🇻', 'timezone' => 'Atlantic/Cape_Verde'],
  ['country' => 'Cambodia', 'dialing_code' => '+855', 'flag' => '🇰🇭', 'timezone' => 'Asia/Phnom_Penh'],
  ['country' => 'Cameroon', 'dialing_code' => '+237', 'flag' => '🇨🇲', 'timezone' => 'Africa/Douala'],
  ['country' => 'Canada', 'dialing_code' => '+1', 'flag' => '🇨🇦', 'timezone' => 'America/Toronto'],
  ['country' => 'Central African Republic', 'dialing_code' => '+236', 'flag' => '🇨🇫', 'timezone' => 'Africa/Bangui'],
  ['country' => 'Chad', 'dialing_code' => '+235', 'flag' => '🇹🇩', 'timezone' => 'Africa/Ndjamena'],
  ['country' => 'Chile', 'dialing_code' => '+56', 'flag' => '🇨🇱', 'timezone' => 'America/Santiago'],
  ['country' => 'China', 'dialing_code' => '+86', 'flag' => '🇨🇳', 'timezone' => 'Asia/Shanghai'],
  ['country' => 'Colombia', 'dialing_code' => '+57', 'flag' => '🇨🇴', 'timezone' => 'America/Bogota'],
  ['country' => 'Comoros', 'dialing_code' => '+269', 'flag' => '🇰🇲', 'timezone' => 'Indian/Comoro'],
  ['country' => 'Congo', 'dialing_code' => '+242', 'flag' => '🇨🇬', 'timezone' => 'Africa/Brazzaville'],
  ['country' => 'Costa Rica', 'dialing_code' => '+506', 'flag' => '🇨🇷', 'timezone' => 'America/Costa_Rica'],
  ['country' => 'Croatia', 'dialing_code' => '+385', 'flag' => '🇭🇷', 'timezone' => 'Europe/Zagreb'],
  ['country' => 'Cuba', 'dialing_code' => '+53', 'flag' => '🇨🇺', 'timezone' => 'America/Havana'],
  ['country' => 'Cyprus', 'dialing_code' => '+357', 'flag' => '🇨🇾', 'timezone' => 'Asia/Nicosia'],
  ['country' => 'Czech Republic', 'dialing_code' => '+420', 'flag' => '🇨🇿', 'timezone' => 'Europe/Prague'],
  ['country' => 'Democratic People\'s Republic of Korea', 'dialing_code' => '+850', 'flag' => '🇰🇵', 'timezone' => 'Asia/Pyongyang'],
  ['country' => 'Democratic Republic of the Congo', 'dialing_code' => '+243', 'flag' => '🇨🇩', 'timezone' => 'Africa/Kinshasa'],
  ['country' => 'Denmark', 'dialing_code' => '+45', 'flag' => '🇩🇰', 'timezone' => 'Europe/Copenhagen'],
  ['country' => 'Djibouti', 'dialing_code' => '+253', 'flag' => '🇩🇯', 'timezone' => 'Africa/Djibouti'],
  ['country' => 'Dominica', 'dialing_code' => '+1', 'flag' => '🇩🇲', 'timezone' => 'America/Dominica'],
  ['country' => 'Dominican Republic', 'dialing_code' => '+1', 'flag' => '🇩🇴', 'timezone' => 'America/Santo_Domingo'],
  ['country' => 'Ecuador', 'dialing_code' => '+593', 'flag' => '🇪🇨', 'timezone' => 'America/Guayaquil'],
  ['country' => 'Egypt', 'dialing_code' => '+20', 'flag' => '🇪🇬', 'timezone' => 'Africa/Cairo'],
  ['country' => 'El Salvador', 'dialing_code' => '+503', 'flag' => '🇸🇻', 'timezone' => 'America/El_Salvador'],
  ['country' => 'Equatorial Guinea', 'dialing_code' => '+240', 'flag' => '🇬🇶', 'timezone' => 'Africa/Malabo'],
  ['country' => 'Eritrea', 'dialing_code' => '+291', 'flag' => '🇪🇷', 'timezone' => 'Africa/Asmara'],
  ['country' => 'Estonia', 'dialing_code' => '+372', 'flag' => '🇪🇪', 'timezone' => 'Europe/Tallinn'],
  ['country' => 'Eswatini', 'dialing_code' => '+268', 'flag' => '🇸🇿', 'timezone' => 'Africa/Mbabane'],
  ['country' => 'Ethiopia', 'dialing_code' => '+251', 'flag' => '🇪🇹', 'timezone' => 'Africa/Addis_Ababa'],
  ['country' => 'Fiji', 'dialing_code' => '+679', 'flag' => '🇫🇯', 'timezone' => 'Pacific/Fiji'],
  ['country' => 'Finland', 'dialing_code' => '+358', 'flag' => '🇫🇮', 'timezone' => 'Europe/Helsinki'],
  ['country' => 'France', 'dialing_code' => '+33', 'flag' => '🇫🇷', 'timezone' => 'Europe/Paris'],
  ['country' => 'Gabon', 'dialing_code' => '+241', 'flag' => '🇬🇦', 'timezone' => 'Africa/Libreville'],
  ['country' => 'Gambia', 'dialing_code' => '+220', 'flag' => '🇬🇲', 'timezone' => 'Africa/Banjul'],
  ['country' => 'Georgia', 'dialing_code' => '+995', 'flag' => '🇬🇪', 'timezone' => 'Asia/Tbilisi'],
  ['country' => 'Germany', 'dialing_code' => '+49', 'flag' => '🇩🇪', 'timezone' => 'Europe/Berlin'],
  ['country' => 'Ghana', 'dialing_code' => '+233', 'flag' => '🇬🇭', 'timezone' => 'Africa/Accra'],
  ['country' => 'Greece', 'dialing_code' => '+30', 'flag' => '🇬🇷', 'timezone' => 'Europe/Athens'],
  ['country' => 'Grenada', 'dialing_code' => '+1', 'flag' => '🇬🇩', 'timezone' => 'America/Grenada'],
  ['country' => 'Guatemala', 'dialing_code' => '+502', 'flag' => '🇬🇹', 'timezone' => 'America/Guatemala'],
  ['country' => 'Guinea', 'dialing_code' => '+224', 'flag' => '🇬🇳', 'timezone' => 'Africa/Conakry'],
  ['country' => 'Guinea-Bissau', 'dialing_code' => '+245', 'flag' => '🇬🇼', 'timezone' => 'Africa/Bissau'],
  ['country' => 'Guyana', 'dialing_code' => '+592', 'flag' => '🇬🇾', 'timezone' => 'America/Guyana'],
  ['country' => 'Haiti', 'dialing_code' => '+509', 'flag' => '🇭🇹', 'timezone' => 'America/Port-au-Prince'],
  ['country' => 'Honduras', 'dialing_code' => '+504', 'flag' => '🇭🇳', 'timezone' => 'America/Tegucigalpa'],
  ['country' => 'Hungary', 'dialing_code' => '+36', 'flag' => '🇭🇺', 'timezone' => 'Europe/Budapest'],
  ['country' => 'Iceland', 'dialing_code' => '+354', 'flag' => '🇮🇸', 'timezone' => 'Atlantic/Reykjavik'],
  ['country' => 'India', 'dialing_code' => '+91', 'flag' => '🇮🇳', 'timezone' => 'Asia/Kolkata'],
  ['country' => 'Indonesia', 'dialing_code' => '+62', 'flag' => '🇮🇩', 'timezone' => 'Asia/Jakarta'],
  ['country' => 'Iran (Islamic Republic of)', 'dialing_code' => '+98', 'flag' => '🇮🇷', 'timezone' => 'Asia/Tehran'],
  ['country' => 'Iraq', 'dialing_code' => '+964', 'flag' => '🇮🇶', 'timezone' => 'Asia/Baghdad'],
  ['country' => 'Ireland', 'dialing_code' => '+353', 'flag' => '🇮🇪', 'timezone' => 'Europe/Dublin'],
  ['country' => 'Israel', 'dialing_code' => '+972', 'flag' => '🇮🇱', 'timezone' => 'Asia/Jerusalem'],
  ['country' => 'Italy', 'dialing_code' => '+39', 'flag' => '🇮🇹', 'timezone' => 'Europe/Rome'],
  ['country' => 'Jamaica', 'dialing_code' => '+1', 'flag' => '🇯🇲', 'timezone' => 'America/Jamaica'],
  ['country' => 'Japan', 'dialing_code' => '+81', 'flag' => '🇯🇵', 'timezone' => 'Asia/Tokyo'],
  ['country' => 'Jordan', 'dialing_code' => '+962', 'flag' => '🇯🇴', 'timezone' => 'Asia/Amman'],
  ['country' => 'Kazakhstan', 'dialing_code' => '+7', 'flag' => '🇰🇿', 'timezone' => 'Asia/Almaty'],
  ['country' => 'Kenya', 'dialing_code' => '+254', 'flag' => '🇰🇪', 'timezone' => 'Africa/Nairobi'],
  ['country' => 'Kiribati', 'dialing_code' => '+686', 'flag' => '🇰🇮', 'timezone' => 'Pacific/Tarawa'],
  ['country' => 'Kuwait', 'dialing_code' => '+965', 'flag' => '🇰🇼', 'timezone' => 'Asia/Kuwait'],
  ['country' => 'Kyrgyzstan', 'dialing_code' => '+996', 'flag' => '🇰🇬', 'timezone' => 'Asia/Bishkek'],
  ['country' => 'Lao People\'s Democratic Republic', 'dialing_code' => '+856', 'flag' => '🇱🇦', 'timezone' => 'Asia/Vientiane'],
  ['country' => 'Latvia', 'dialing_code' => '+371', 'flag' => '🇱🇻', 'timezone' => 'Europe/Riga'],
  ['country' => 'Lebanon', 'dialing_code' => '+961', 'flag' => '🇱🇧', 'timezone' => 'Asia/Beirut'],
  ['country' => 'Lesotho', 'dialing_code' => '+266', 'flag' => '🇱🇸', 'timezone' => 'Africa/Maseru'],
  ['country' => 'Liberia', 'dialing_code' => '+231', 'flag' => '🇱🇷', 'timezone' => 'Africa/Monrovia'],
  ['country' => 'Libya', 'dialing_code' => '+218', 'flag' => '🇱🇾', 'timezone' => 'Africa/Tripoli'],
  ['country' => 'Liechtenstein', 'dialing_code' => '+423', 'flag' => '🇱🇮', 'timezone' => 'Europe/Vaduz'],
  ['country' => 'Lithuania', 'dialing_code' => '+370', 'flag' => '🇱🇹', 'timezone' => 'Europe/Vilnius'],
  ['country' => 'Luxembourg', 'dialing_code' => '+352', 'flag' => '🇱🇺', 'timezone' => 'Europe/Luxembourg'],
  ['country' => 'Madagascar', 'dialing_code' => '+261', 'flag' => '🇲🇬', 'timezone' => 'Indian/Antananarivo'],
  ['country' => 'Malawi', 'dialing_code' => '+265', 'flag' => '🇲🇼', 'timezone' => 'Africa/Blantyre'],
  ['country' => 'Malaysia', 'dialing_code' => '+60', 'flag' => '🇲🇾', 'timezone' => 'Asia/Kuala_Lumpur'],
  ['country' => 'Maldives', 'dialing_code' => '+960', 'flag' => '🇲🇻', 'timezone' => 'Indian/Maldives'],
  ['country' => 'Mali', 'dialing_code' => '+223', 'flag' => '🇲🇱', 'timezone' => 'Africa/Bamako'],
  ['country' => 'Malta', 'dialing_code' => '+356', 'flag' => '🇲🇹', 'timezone' => 'Europe/Malta'],
  ['country' => 'Marshall Islands', 'dialing_code' => '+692', 'flag' => '🇲🇭', 'timezone' => 'Pacific/Majuro'],
  ['country' => 'Mauritania', 'dialing_code' => '+222', 'flag' => '🇲🇷', 'timezone' => 'Africa/Nouakchott'],
  ['country' => 'Mauritius', 'dialing_code' => '+230', 'flag' => '🇲🇺', 'timezone' => 'Indian/Mauritius'],
  ['country' => 'Mexico', 'dialing_code' => '+52', 'flag' => '🇲🇽', 'timezone' => 'America/Mexico_City'],
  ['country' => 'Micronesia (Federated States of)', 'dialing_code' => '+691', 'flag' => '🇫🇲', 'timezone' => 'Pacific/Chuuk'],
  ['country' => 'Monaco', 'dialing_code' => '+377', 'flag' => '🇲🇨', 'timezone' => 'Europe/Monaco'],
  ['country' => 'Mongolia', 'dialing_code' => '+976', 'flag' => '🇲🇳', 'timezone' => 'Asia/Ulaanbaatar'],
  ['country' => 'Montenegro', 'dialing_code' => '+382', 'flag' => '🇲🇪', 'timezone' => 'Europe/Podgorica'],
  ['country' => 'Morocco', 'dialing_code' => '+212', 'flag' => '🇲🇦', 'timezone' => 'Africa/Casablanca'],
  ['country' => 'Mozambique', 'dialing_code' => '+258', 'flag' => '🇲🇿', 'timezone' => 'Africa/Maputo'],
  ['country' => 'Myanmar', 'dialing_code' => '+95', 'flag' => '🇲🇲', 'timezone' => 'Asia/Yangon'],
  ['country' => 'Namibia', 'dialing_code' => '+264', 'flag' => '🇳🇦', 'timezone' => 'Africa/Windhoek'],
  ['country' => 'Nauru', 'dialing_code' => '+674', 'flag' => '🇳🇷', 'timezone' => 'Pacific/Nauru'],
  ['country' => 'Nepal', 'dialing_code' => '+977', 'flag' => '🇳🇵', 'timezone' => 'Asia/Kathmandu'],
  ['country' => 'Netherlands', 'dialing_code' => '+31', 'flag' => '🇳🇱', 'timezone' => 'Europe/Amsterdam'],
  ['country' => 'New Zealand', 'dialing_code' => '+64', 'flag' => '🇳🇿', 'timezone' => 'Pacific/Auckland'],
  ['country' => 'Nicaragua', 'dialing_code' => '+505', 'flag' => '🇳🇮', 'timezone' => 'America/Managua'],
  ['country' => 'Niger', 'dialing_code' => '+227', 'flag' => '🇳🇪', 'timezone' => 'Africa/Niamey'],
  ['country' => 'Nigeria', 'dialing_code' => '+234', 'flag' => '🇳🇬', 'timezone' => 'Africa/Lagos'],
  ['country' => 'North Macedonia', 'dialing_code' => '+389', 'flag' => '🇲🇰', 'timezone' => 'Europe/Skopje'],
  ['country' => 'Norway', 'dialing_code' => '+47', 'flag' => '🇳🇴', 'timezone' => 'Europe/Oslo'],
  ['country' => 'Oman', 'dialing_code' => '+968', 'flag' => '🇴🇲', 'timezone' => 'Asia/Muscat'],
  ['country' => 'Pakistan', 'dialing_code' => '+92', 'flag' => '🇵🇰', 'timezone' => 'Asia/Karachi'],
  ['country' => 'Palau', 'dialing_code' => '+680', 'flag' => '🇵🇼', 'timezone' => 'Pacific/Palau'],
  ['country' => 'Panama', 'dialing_code' => '+507', 'flag' => '🇵🇦', 'timezone' => 'America/Panama'],
  ['country' => 'Papua New Guinea', 'dialing_code' => '+675', 'flag' => '🇵🇬', 'timezone' => 'Pacific/Port_Moresby'],
  ['country' => 'Paraguay', 'dialing_code' => '+595', 'flag' => '🇵🇾', 'timezone' => 'America/Asuncion'],
  ['country' => 'Peru', 'dialing_code' => '+51', 'flag' => '🇵🇪', 'timezone' => 'America/Lima'],
  ['country' => 'Philippines', 'dialing_code' => '+63', 'flag' => '🇵🇭', 'timezone' => 'Asia/Manila'],
  ['country' => 'Poland', 'dialing_code' => '+48', 'flag' => '🇵🇱', 'timezone' => 'Europe/Warsaw'],
  ['country' => 'Portugal', 'dialing_code' => '+351', 'flag' => '🇵🇹', 'timezone' => 'Europe/Lisbon'],
  ['country' => 'Qatar', 'dialing_code' => '+974', 'flag' => '🇶🇦', 'timezone' => 'Asia/Qatar'],
  ['country' => 'Republic of Korea', 'dialing_code' => '+82', 'flag' => '🇰🇷', 'timezone' => 'Asia/Seoul'],
  ['country' => 'Republic of Moldova', 'dialing_code' => '+373', 'flag' => '🇲🇩', 'timezone' => 'Europe/Chisinau'],
  ['country' => 'Romania', 'dialing_code' => '+40', 'flag' => '🇷🇴', 'timezone' => 'Europe/Bucharest'],
  ['country' => 'Russian Federation', 'dialing_code' => '+7', 'flag' => '🇷🇺', 'timezone' => 'Europe/Moscow'],
  ['country' => 'Rwanda', 'dialing_code' => '+250', 'flag' => '🇷🇼', 'timezone' => 'Africa/Kigali'],
  ['country' => 'Saint Kitts and Nevis', 'dialing_code' => '+1', 'flag' => '🇰🇳', 'timezone' => 'America/St_Kitts'],
  ['country' => 'Saint Lucia', 'dialing_code' => '+1', 'flag' => '🇱🇨', 'timezone' => 'America/St_Lucia'],
  ['country' => 'Saint Vincent and the Grenadines', 'dialing_code' => '+1', 'flag' => '🇻🇨', 'timezone' => 'America/St_Vincent'],
  ['country' => 'Samoa', 'dialing_code' => '+685', 'flag' => '🇼🇸', 'timezone' => 'Pacific/Apia'],
  ['country' => 'San Marino', 'dialing_code' => '+378', 'flag' => '🇸🇲', 'timezone' => 'Europe/San_Marino'],
  ['country' => 'Sao Tome and Principe', 'dialing_code' => '+239', 'flag' => '🇸🇹', 'timezone' => 'Africa/Sao_Tome'],
  ['country' => 'Saudi Arabia', 'dialing_code' => '+966', 'flag' => '🇸🇦', 'timezone' => 'Asia/Riyadh'],
  ['country' => 'Senegal', 'dialing_code' => '+221', 'flag' => '🇸🇳', 'timezone' => 'Africa/Dakar'],
  ['country' => 'Serbia', 'dialing_code' => '+381', 'flag' => '🇷🇸', 'timezone' => 'Europe/Belgrade'],
  ['country' => 'Seychelles', 'dialing_code' => '+248', 'flag' => '🇸🇨', 'timezone' => 'Indian/Mahe'],
  ['country' => 'Sierra Leone', 'dialing_code' => '+232', 'flag' => '🇸🇱', 'timezone' => 'Africa/Freetown'],
  ['country' => 'Singapore', 'dialing_code' => '+65', 'flag' => '🇸🇬', 'timezone' => 'Asia/Singapore'],
  ['country' => 'Slovakia', 'dialing_code' => '+421', 'flag' => '🇸🇰', 'timezone' => 'Europe/Bratislava'],
  ['country' => 'Slovenia', 'dialing_code' => '+386', 'flag' => '🇸🇮', 'timezone' => 'Europe/Ljubljana'],
  ['country' => 'Solomon Islands', 'dialing_code' => '+677', 'flag' => '🇸🇧', 'timezone' => 'Pacific/Guadalcanal'],
  ['country' => 'Somalia', 'dialing_code' => '+252', 'flag' => '🇸🇴', 'timezone' => 'Africa/Mogadishu'],
  ['country' => 'South Africa', 'dialing_code' => '+27', 'flag' => '🇿🇦', 'timezone' => 'Africa/Johannesburg'],
  ['country' => 'South Sudan', 'dialing_code' => '+211', 'flag' => '🇸🇸', 'timezone' => 'Africa/Juba'],
  ['country' => 'Spain', 'dialing_code' => '+34', 'flag' => '🇪🇸', 'timezone' => 'Europe/Madrid'],
  ['country' => 'Sri Lanka', 'dialing_code' => '+94', 'flag' => '🇱🇰', 'timezone' => 'Asia/Colombo'],
  ['country' => 'Sudan', 'dialing_code' => '+249', 'flag' => '🇸🇩', 'timezone' => 'Africa/Khartoum'],
  ['country' => 'Suriname', 'dialing_code' => '+597', 'flag' => '🇸🇷', 'timezone' => 'America/Paramaribo'],
  ['country' => 'Sweden', 'dialing_code' => '+46', 'flag' => '🇸🇪', 'timezone' => 'Europe/Stockholm'],
  ['country' => 'Switzerland', 'dialing_code' => '+41', 'flag' => '🇨🇭', 'timezone' => 'Europe/Zurich'],
  ['country' => 'Syrian Arab Republic', 'dialing_code' => '+963', 'flag' => '🇸🇾', 'timezone' => 'Asia/Damascus'],
  ['country' => 'Tajikistan', 'dialing_code' => '+992', 'flag' => '🇹🇯', 'timezone' => 'Asia/Dushanbe'],
  ['country' => 'Thailand', 'dialing_code' => '+66', 'flag' => '🇹🇭', 'timezone' => 'Asia/Bangkok'],
  ['country' => 'Timor-Leste', 'dialing_code' => '+670', 'flag' => '🇹🇱', 'timezone' => 'Asia/Dili'],
  ['country' => 'Togo', 'dialing_code' => '+228', 'flag' => '🇹🇬', 'timezone' => 'Africa/Lome'],
  ['country' => 'Tonga', 'dialing_code' => '+676', 'flag' => '🇹🇴', 'timezone' => 'Pacific/Tongatapu'],
  ['country' => 'Trinidad and Tobago', 'dialing_code' => '+1', 'flag' => '🇹🇹', 'timezone' => 'America/Port_of_Spain'],
  ['country' => 'Tunisia', 'dialing_code' => '+216', 'flag' => '🇹🇳', 'timezone' => 'Africa/Tunis'],
  ['country' => 'Turkey', 'dialing_code' => '+90', 'flag' => '🇹🇷', 'timezone' => 'Europe/Istanbul'],
  ['country' => 'Turkmenistan', 'dialing_code' => '+993', 'flag' => '🇹🇲', 'timezone' => 'Asia/Ashgabat'],
  ['country' => 'Tuvalu', 'dialing_code' => '+688', 'flag' => '🇹🇻', 'timezone' => 'Pacific/Funafuti'],
  ['country' => 'Uganda', 'dialing_code' => '+256', 'flag' => '🇺🇬', 'timezone' => 'Africa/Kampala'],
  ['country' => 'Ukraine', 'dialing_code' => '+380', 'flag' => '🇺🇦', 'timezone' => 'Europe/Kiev'],
  ['country' => 'United Arab Emirates', 'dialing_code' => '+971', 'flag' => '🇦🇪', 'timezone' => 'Asia/Dubai'],
  ['country' => 'United Kingdom', 'dialing_code' => '+44', 'flag' => '🇬🇧', 'timezone' => 'Europe/London'],
  ['country' => 'United Republic of Tanzania', 'dialing_code' => '+255', 'flag' => '🇹🇿', 'timezone' => 'Africa/Dar_es_Salaam'],
  ['country' => 'United States of America', 'dialing_code' => '+1', 'flag' => '🇺🇸', 'timezone' => 'America/New_York'],
  ['country' => 'Uruguay', 'dialing_code' => '+598', 'flag' => '🇺🇾', 'timezone' => 'America/Montevideo'],
  ['country' => 'Uzbekistan', 'dialing_code' => '+998', 'flag' => '🇺🇿', 'timezone' => 'Asia/Tashkent'],
  ['country' => 'Vanuatu', 'dialing_code' => '+678', 'flag' => '🇻🇺', 'timezone' => 'Pacific/Efate'],
  ['country' => 'Venezuela (Bolivarian Republic of)', 'dialing_code' => '+58', 'flag' => '🇻🇪', 'timezone' => 'America/Caracas'],
  ['country' => 'Viet Nam', 'dialing_code' => '+84', 'flag' => '🇻🇳', 'timezone' => 'Asia/Ho_Chi_Minh'],
  ['country' => 'Yemen', 'dialing_code' => '+967', 'flag' => '🇾🇪', 'timezone' => 'Asia/Aden'],
  ['country' => 'Zambia', 'dialing_code' => '+260', 'flag' => '🇿🇲', 'timezone' => 'Africa/Lusaka'],
  ['country' => 'Zimbabwe', 'dialing_code' => '+263', 'flag' => '🇿🇼', 'timezone' => 'Africa/Harare'],
];
